# Generated by Django 3.2.8 on 2021-11-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('picture', models.URLField(max_length=255)),
                ('author', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('language', models.CharField(choices=[('en', 'English'), ('lk', 'Sinhala'), ('tm', 'Tamil'), ('sp', 'Spanish'), ('gr', 'German'), ('fr', 'French'), ('ru', 'Russian'), ('lt', 'Latin'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('ot', 'Other')], max_length=2)),
                ('description', models.TextField(max_length=512)),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField()),
                ('issued', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.books')),
            ],
        ),
    ]
