# Generated by Django 3.2.8 on 2021-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211104_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='availability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='issued',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='availability',
        ),
    ]
