# Generated by Django 3.2.9 on 2021-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_books_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
